# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'friend.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FriendsWindow(object):
    def setupUi(self, FriendsWindow):
        FriendsWindow.setObjectName("FriendsWindow")
        FriendsWindow.resize(350, 500)
        self.centralwidget = QtWidgets.QWidget(FriendsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(60, 410, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.confirmButton.setFont(font)
        self.confirmButton.setObjectName("confirmButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(75, 130, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_text = QtWidgets.QLabel(self.centralwidget)
        self.label_text.setGeometry(QtCore.QRect(30, 60, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_text.setFont(font)
        self.label_text.setText("")
        self.label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text.setObjectName("label_text")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(10, 10, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.friend_id = QtWidgets.QLineEdit(self.centralwidget)
        self.friend_id.setGeometry(QtCore.QRect(50, 280, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.friend_id.setFont(font)
        self.friend_id.setObjectName("friend_id")
        self.friend_name = QtWidgets.QLineEdit(self.centralwidget)
        self.friend_name.setGeometry(QtCore.QRect(50, 160, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.friend_name.setFont(font)
        self.friend_name.setObjectName("friend_name")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(75, 250, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        FriendsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FriendsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        FriendsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FriendsWindow)
        self.statusbar.setObjectName("statusbar")
        FriendsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FriendsWindow)
        QtCore.QMetaObject.connectSlotsByName(FriendsWindow)

    def retranslateUi(self, FriendsWindow):
        _translate = QtCore.QCoreApplication.translate
        FriendsWindow.setWindowTitle(_translate("FriendsWindow", "MainWindow"))
        self.confirmButton.setText(_translate("FriendsWindow", "Подтвердить"))
        self.label_3.setText(_translate("FriendsWindow", "Имя вашего друга"))
        self.backButton.setText(_translate("FriendsWindow", "Назад"))
        self.label_4.setText(_translate("FriendsWindow", "ID вашего друга"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FriendsWindow = QtWidgets.QMainWindow()
    ui = Ui_FriendsWindow()
    ui.setupUi(FriendsWindow)
    FriendsWindow.show()
    sys.exit(app.exec_())
