# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingsWindow(object):
    def setupUi(self, settingsWindow):
        settingsWindow.setObjectName("settingsWindow")
        settingsWindow.resize(350, 500)
        self.centralwidget = QtWidgets.QWidget(settingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backsettingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.backsettingsButton.setGeometry(QtCore.QRect(10, 10, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.backsettingsButton.setFont(font)
        self.backsettingsButton.setObjectName("backsettingsButton")
        self.pidButton = QtWidgets.QPushButton(self.centralwidget)
        self.pidButton.setGeometry(QtCore.QRect(60, 380, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pidButton.setFont(font)
        self.pidButton.setObjectName("pidButton")
        self.passwordButton = QtWidgets.QPushButton(self.centralwidget)
        self.passwordButton.setGeometry(QtCore.QRect(60, 250, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.passwordButton.setFont(font)
        self.passwordButton.setObjectName("passwordButton")
        self.nameButton = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton.setGeometry(QtCore.QRect(60, 120, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.nameButton.setFont(font)
        self.nameButton.setObjectName("nameButton")
        settingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(settingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        settingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(settingsWindow)
        self.statusbar.setObjectName("statusbar")
        settingsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(settingsWindow)
        QtCore.QMetaObject.connectSlotsByName(settingsWindow)

    def retranslateUi(self, settingsWindow):
        _translate = QtCore.QCoreApplication.translate
        settingsWindow.setWindowTitle(_translate("settingsWindow", "MainWindow"))
        self.backsettingsButton.setText(_translate("settingsWindow", "Назад"))
        self.pidButton.setText(_translate("settingsWindow", "Узнать мой ID"))
        self.passwordButton.setText(_translate("settingsWindow", "Изменить пароль"))
        self.nameButton.setText(_translate("settingsWindow", "Изменить имя"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settingsWindow = QtWidgets.QMainWindow()
    ui = Ui_settingsWindow()
    ui.setupUi(settingsWindow)
    settingsWindow.show()
    sys.exit(app.exec_())
