# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'id.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pidWindow(object):
    def setupUi(self, pidWindow):
        pidWindow.setObjectName("pidWindow")
        pidWindow.resize(350, 500)
        self.centralwidget = QtWidgets.QWidget(pidWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(10, 10, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.label_text = QtWidgets.QLabel(self.centralwidget)
        self.label_text.setGeometry(QtCore.QRect(30, 60, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_text.setFont(font)
        self.label_text.setText("")
        self.label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text.setObjectName("label_text")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(75, 180, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(75, 110, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.password_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.password_2.setGeometry(QtCore.QRect(50, 210, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_2.setFont(font)
        self.password_2.setObjectName("password_2")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(50, 140, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password.setFont(font)
        self.password.setText("")
        self.password.setObjectName("password")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(60, 380, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.confirmButton.setFont(font)
        self.confirmButton.setObjectName("confirmButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 290, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        pidWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(pidWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        pidWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(pidWindow)
        self.statusbar.setObjectName("statusbar")
        pidWindow.setStatusBar(self.statusbar)

        self.retranslateUi(pidWindow)
        QtCore.QMetaObject.connectSlotsByName(pidWindow)

    def retranslateUi(self, pidWindow):
        _translate = QtCore.QCoreApplication.translate
        pidWindow.setWindowTitle(_translate("pidWindow", "MainWindow"))
        self.backButton.setText(_translate("pidWindow", "Назад"))
        self.label_2.setText(_translate("pidWindow", "Подтвердите пароль"))
        self.label_3.setText(_translate("pidWindow", "Введите пароль"))
        self.confirmButton.setText(_translate("pidWindow", "Подтвердить"))
        self.label.setText(_translate("pidWindow", "ID:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pidWindow = QtWidgets.QMainWindow()
    ui = Ui_pidWindow()
    ui.setupUi(pidWindow)
    pidWindow.show()
    sys.exit(app.exec_())
