# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'online.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_onlineWindow(object):
    def setupUi(self, onlineWindow):
        onlineWindow.setObjectName("onlineWindow")
        onlineWindow.resize(350, 500)
        self.centralwidget = QtWidgets.QWidget(onlineWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 40, 331, 421))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(10, 10, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(105, 3, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.updateButton.setFont(font)
        self.updateButton.setObjectName("updateButton")
        onlineWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(onlineWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        onlineWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(onlineWindow)
        self.statusbar.setObjectName("statusbar")
        onlineWindow.setStatusBar(self.statusbar)

        self.retranslateUi(onlineWindow)
        QtCore.QMetaObject.connectSlotsByName(onlineWindow)

    def retranslateUi(self, onlineWindow):
        _translate = QtCore.QCoreApplication.translate
        onlineWindow.setWindowTitle(_translate("onlineWindow", "MainWindow"))
        self.backButton.setText(_translate("onlineWindow", "Назад"))
        self.updateButton.setText(_translate("onlineWindow", "Обновить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    onlineWindow = QtWidgets.QMainWindow()
    ui = Ui_onlineWindow()
    ui.setupUi(onlineWindow)
    onlineWindow.show()
    sys.exit(app.exec_())
