# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistWindow(object):
    def setupUi(self, RegistWindow):
        RegistWindow.setObjectName("RegistWindow")
        RegistWindow.resize(350, 500)
        self.centralwidget = QtWidgets.QWidget(RegistWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 180, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(40, 140, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name.setFont(font)
        self.name.setText("")
        self.name.setObjectName("name")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 110, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(40, 210, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.log_inButton = QtWidgets.QPushButton(self.centralwidget)
        self.log_inButton.setGeometry(QtCore.QRect(60, 380, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.log_inButton.setFont(font)
        self.log_inButton.setObjectName("log_inButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 260, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.password_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.password_2.setGeometry(QtCore.QRect(40, 290, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_2.setFont(font)
        self.password_2.setObjectName("password_2")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(10, 10, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.label_text = QtWidgets.QLabel(self.centralwidget)
        self.label_text.setGeometry(QtCore.QRect(30, 60, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_text.setFont(font)
        self.label_text.setText("")
        self.label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text.setObjectName("label_text")
        RegistWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RegistWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        RegistWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RegistWindow)
        self.statusbar.setObjectName("statusbar")
        RegistWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RegistWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistWindow)

    def retranslateUi(self, RegistWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistWindow.setWindowTitle(_translate("RegistWindow", "MainWindow"))
        self.label_2.setText(_translate("RegistWindow", "Пароль"))
        self.label.setText(_translate("RegistWindow", "Логин"))
        self.log_inButton.setText(_translate("RegistWindow", "Подтвердить"))
        self.label_3.setText(_translate("RegistWindow", "Подтвердите пароль"))
        self.backButton.setText(_translate("RegistWindow", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistWindow = QtWidgets.QMainWindow()
    ui = Ui_RegistWindow()
    ui.setupUi(RegistWindow)
    RegistWindow.show()
    sys.exit(app.exec_())
